### ISSUE TITLE
Updating README.md

### ISSUE THREAD

**Issue by AlphaVS-76** [PyImageSearch/Deep-Learning-for-Computer-Vision-with-Python#19]
## Describe the issue 

The FAQs section in [README.md](https://github.com/PyImageSearch/Deep-Learning-for-Computer-Vision-with-Python/blob/main/README.md) could use an inline link for community forum.

### Additional Changes
- Corresponding headers would also look static in the [README.md](https://github.com/PyImageSearch/Deep-Learning-for-Computer-Vision-with-Python/blob/main/README.md) section

### Assignees

- I would be glad if this was assigned to me.

**Comment by vikaskookna** [comment]
@AlphaVS-76 Link to community added, thanks for letting us know.
