### ISSUE TITLE
ImportError: No module named sklearn.preprocessing

### ISSUE THREAD

**Issue by alexlev2004** [PyImageSearch/Deep-Learning-for-Computer-Vision-with-Python#3]
## Are you using one of our development environments? 

Yes. I am using VM, downloaded about a week ago.

## If you are using your own development environment then please provide the following details.

N/A

## Describe the issue 

Running chapter 7's knn.py I am getting error:

ImportError: No module named sklearn.preprocessing

## Any other information

Looking into the problem, I realized that actually I need to run:

"**python3** knn.py --dataset ../datasets/animals" and not as instructed in the book "python knn.py --dataset ../datasets/animals"

As default python version is 2.7.

**Comment by sayakpaul** [comment]
You first need to activate the Python virtual environment to start working with the chapters. You can run the `lsvirtualenv` command to see a list of the Python virtual environments present there.
