### ISSUE TITLE
tf.io.TFRecordWriter(outputPath) issue

### ISSUE THREAD

**Issue by splash1123** [PyImageSearch/Deep-Learning-for-Computer-Vision-with-Python#4]
_Please use this template while reporting bugs inside DL4CV. Issues related to personal project questions or code that we haven't authored will automatically be closed._

## Are you using one of our development environments? 

We provide a preconfigured AWS AMI and a VM to help our customers skip the environment setup part and jump straight to development. We highly suggest using one of our development environments to run our code. 

If the issue is not related to code, then you can simply skip this question. 

## If you are using your own development environment then please provide the following details.

* GPU model and CUDA version: (skip if not application) 
* OS Platform: 
* Python version: 
* OpenCV version: 
* TensorFlow version:

## Describe the issue 
Hi,
Recently i have tried to train a faster rcnn model, but when i run the code, writer = tf.io.TFRecordWriter(outputPath), which is in the imagenet bundle(chapter 15.3 Training Your Faster R-CNN). It reported that the "outputPath" is a "directory" not a "path", but i can't see what the difference between the path and the directory, because they are all strings of paths.

This line of code is in imagenet bundle(chapter 15.3 Training Your Faster R-CNN Page 271).

Thank you in advance!
Best,
Drew Yang

**Comment by sayakpaul** [comment]
@splash1123 are you using one of our virtual machines for DL4CV? 

Also, could you log what you are getting as `outputPath`?

**Comment by splash1123** [comment]
@sayakpaul thanks, the issue is solved.

**Comment by sayakpaul** [comment]
Wonderful.
